--H2
SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE url_check RESTART IDENTITY
;
TRUNCATE TABLE url RESTART IDENTITY
;

--Postgres
--TRUNCATE TABLE url_check CASCADE;
--ALTER SEQUENCE url_check_id_seq RESTART;
--
--TRUNCATE TABLE url CASCADE;
--ALTER SEQUENCE url_id_seq RESTART;